//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proba3
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Город.
    /// </summary>
    // *** Start programmer edit section *** (Город CustomAttributes)

    // *** End programmer edit section *** (Город CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ГородE", new string[] {
            "Назв as \'Назв\'",
            "Улица as \'Улица\'",
            "Улица.Назв as \'Назв\'"}, Hidden=new string[] {
            "Улица.Назв"})]
    [MasterViewDefineAttribute("ГородE", "Улица", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Назв")]
    [View("ГородL", new string[] {
            "Назв as \'Назв\'",
            "Улица.Назв as \'Назв\'"})]
    public class Город : ICSSoft.STORMNET.DataObject
    {
        
        private string fНазв;
        
        private IIS.Proba3.Улица fУлица;
        
        // *** Start programmer edit section *** (Город CustomMembers)

        // *** End programmer edit section *** (Город CustomMembers)

        
        /// <summary>
        /// Назв.
        /// </summary>
        // *** Start programmer edit section *** (Город.Назв CustomAttributes)

        // *** End programmer edit section *** (Город.Назв CustomAttributes)
        [StrLen(255)]
        public virtual string Назв
        {
            get
            {
                // *** Start programmer edit section *** (Город.Назв Get start)

                // *** End programmer edit section *** (Город.Назв Get start)
                string result = this.fНазв;
                // *** Start programmer edit section *** (Город.Назв Get end)

                // *** End programmer edit section *** (Город.Назв Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Город.Назв Set start)

                // *** End programmer edit section *** (Город.Назв Set start)
                this.fНазв = value;
                // *** Start programmer edit section *** (Город.Назв Set end)

                // *** End programmer edit section *** (Город.Назв Set end)
            }
        }
        
        /// <summary>
        /// Город.
        /// </summary>
        // *** Start programmer edit section *** (Город.Улица CustomAttributes)

        // *** End programmer edit section *** (Город.Улица CustomAttributes)
        [PropertyStorage(new string[] {
                "Улица"})]
        [NotNull()]
        public virtual IIS.Proba3.Улица Улица
        {
            get
            {
                // *** Start programmer edit section *** (Город.Улица Get start)

                // *** End programmer edit section *** (Город.Улица Get start)
                IIS.Proba3.Улица result = this.fУлица;
                // *** Start programmer edit section *** (Город.Улица Get end)

                // *** End programmer edit section *** (Город.Улица Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Город.Улица Set start)

                // *** End programmer edit section *** (Город.Улица Set start)
                this.fУлица = value;
                // *** Start programmer edit section *** (Город.Улица Set end)

                // *** End programmer edit section *** (Город.Улица Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ГородE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ГородE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ГородE", typeof(IIS.Proba3.Город));
                }
            }
            
            /// <summary>
            /// "ГородL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ГородL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ГородL", typeof(IIS.Proba3.Город));
                }
            }
        }
    }
}
